config/routes.rb
Rails.application.routes.draw do
  root "root#index"
  resources :messages do
    resources :comments
  end
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
end

app/models/message.rb
class Message < ApplicationRecord
  has_many :comments
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_message, only: %i[ index new create ]

  def index
  end

  def new
    @comment = @message.comments.new
  end

  def create
    @comment = @message.comments.create!(comment_params)
    redirect_to message_comments_path(@message)
  end

  private

  def set_message
    @message = Message.find(params[:message_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages
  def index
    @messages = Message.all
  end

  # GET /messages/1
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to @message, notice: "Message was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /messages/1
  def update
    if @message.update(message_params)
      redirect_to @message, notice: "Message was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy
    redirect_to messages_url, notice: "Message was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_url(@post), notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy

    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p id="<%= dom_id comment %>">
  <%= comment.created_at.to_formatted_s(:shor)%>: <%=comment.content %>
</p>

app/views/comments/index.html.erb
<h1>Comments</h1>

<%= turbo_frame_tag 'comments' do %>
  <div id="comments">
    <%= render @message.comments %>
    <%= link_to "New Comment", new_message_comment_path(@message) %>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= turbo_frame_tag 'comments' do%>
  <%= form_with(model: [@comment.message, @comment]) do |form| %>
    <div>
      <%= form.label :content, style: "display: block" %>
      <%= form.text_field :content %>
    </div>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  
  <%= link_to 'back', message_comments_path(@message) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireRailsSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar">
      <div class="container-fluid">
        <a href="<%= root_path %>" class="navbar-brand">HotwireRailsSample</a>
        <div>
          <ul class="navbar-nav">
            <li class="nav-item"><a href="<%= posts_path %>" class="nav-link">Posts</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container my-md-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<h1><%= message.title %></h1>
<p><%= message.content %></p>
<a href="<%= edit_message_path(message) %>">Edit this message</a>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= turbo_frame_tag @message do %>
  <%= render "form", message: @message %>
<% end %>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= turbo_frame_tag @message do %>
  <%= render @message %>
<% end %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

<%= turbo_frame_tag 'comments', src: message_comments_path(@message) %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :body, for: 'bodyInputTextarea', class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control', id: 'bodyInputTextarea' %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <th id="<%= dom_id post %>"><%= link_to post.id, post %></th>
  <td><%= post.body %></td>
</tr>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<% if @posts.present? %>
  <table class="table" id="posts">
    <thead>
      <tr>
        <th>#</th>
        <th>body</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <%= render post %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div>empty</div>
<% end %>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/root/index.html.erb
<h1>Rootページ</h1>